module is reused, no need to exclude mehtod
[strap.library] Compiling 581 files to /Users/adriaan/git/scala/build/strap/classes/library
[strap.library] /Users/adriaan/git/scala/src/library/scala/collection/convert/Wrappers.scala:431: error: Unexpected tree on the RHS of a module accessor: {
[strap.library]   <synthetic> val _$this: scala.collection.convert.Wrappers.type = Wrappers.this;
[strap.library]   _IteratorWrapper(_$this: scala.collection.convert.Wrappers.type){
[strap.library]     (_IteratorWrapper(Wrappers.this): scala.collection.convert.Wrappers#IteratorWrapper.type)
[strap.library]   }
[strap.library] }
[strap.library] object Wrappers extends Wrappers with Serializable
[strap.library]        ^
[strap.library] /Users/adriaan/git/scala/src/library/scala/sys/process/Process.scala:41: error: Unexpected tree on the RHS of a module accessor: {
[strap.library]   <synthetic> val _$this: scala.sys.process.Process.type = Process.this;
[strap.library]   _Spawn(_$this: scala.sys.process.Process.type){
[strap.library]     (_Spawn(Process.this): scala.sys.process.ProcessImpl#Spawn.type)
[strap.library]   }
[strap.library] }
[strap.library] object Process extends ProcessImpl with ProcessCreation { }
[strap.library]        ^
[strap.library] two errors found